main: br.com.eterniaserver.eterniacrates.EterniaCrates

name: EterniaCrates
version: "${version}"
dev-url: https://github.com/EterniaServer/EterniaCrates
author: Yuri Nogueira
description: A basic crate plugin
api-version: "1.20"
depend: [EterniaLib]