main: br.com.eterniaserver.eterniacrates.EterniaCrates

name: EterniaCrates
version: '${project.version}'
author: Yuri Nogueira
description: A Basic Crates Plugid
api-version: '1.16'
depend: [EterniaLib]